<p><b>Important Information</b><br/>
You should carefully read the following Terms and Conditions. Your purchase or use of our products implies that you have read and accepted these Terms and Conditions.</p>

<p><b>Introduction</b><br/>
Our basic service is free, and we offer paid upgrades for advanced features such as domain hosting and extra storage. Our service is designed to give your club as much control and ownership over what goes on your site as possible and encourage your members to express themselves freely. However, each club must be responsible for the content of their site. In particular, make sure that none of the prohibited items listed below appear on your site or get linked to from your site (things like spam, viruses, or hate content).</p>
<p>The following terms and conditions govern all use of the [website-name] website and all content, services and products available at or through the website. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, [website-name] Privacy Policy).
Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by [website-name], acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>

<p><b>Ownership</b><br/>
You do not claim intellectual property right or exclusive ownership to any of our products, modified or unmodified. All products are property of [website-name]. Our products are provided \'as is\' without warranty of any kind, either expressed or implied. In no event shall our company be liable for any damages including, but not limited to, direct, indirect, special, punitive, incidental or consequential, or other losses arising out of the use of or inability to use our products.</p>

<p><b>Your [website-name] Account and Site.</b><br/>
If you create a site with [website-name], you are responsible for maintaining the security of your account and site, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the site. You must not describe or assign keywords to your site in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and [website-name] may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause [website-name] liability. You must immediately notify [website-name] of any unauthorized uses of your site, your account or any other breaches of security. [website-name] will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.</p>

<p><b>Responsibility of Contributors.</b><br/>
If you operate a website, comment on a website, post material to the website, post links on the website, or otherwise make (or allow any third party to make) material available by means of the website (any such material, \'Content\'), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:</p>
<ul>
<li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
<li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
<li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;
the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
<li>the Content is not obscene, libelous or defamatory, hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party;</li>
<li>your site is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your site\'s URL or name is not the name of a person other than yourself or company other than your own; and</li>
<li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by [website-name] or otherwise.</li>
</ul>
<p>By submitting Content to [website-name] for inclusion on your Website, you grant [website-name] a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your site. If you delete Content, [website-name] will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</li>
Without limiting any of those representations or warranties, [website-name] has the right (though not the obligation) to, in [website-name]\'s sole discretion (i) refuse or remove any content that, in [website-name]\'s reasonable opinion, violates any [website-name] policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in [website-name]\'s sole discretion. [website-name] will have no obligation to provide a refund of any amounts previously paid.</p>

<p><b>Fees and Payment.</b><br/>
Optional premium paid services such as extra storage, domain purchases or VIP hosting are available on the Website. By selecting a premium service you agree to pay [website-name] the monthly or annual subscription fees indicated for that service. Payments will be charged on the day you sign up for a premium service and will cover the use of that service for a monthly or annual period as indicated. Premium service fees are not refundable.</p>

<p><b>Responsibility of Website Visitors.</b><br/>
[website-name] has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material\'s content, use or effects. By operating the Website, [website-name] does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. [website-name] disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</p>

<p><b>Content Posted on Other Websites.</b><br/>
We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and WebPages to which [website-name] links, and that link to [website-name]. [website-name] does not have any control over those non- [website-name] websites and WebPages, and is not responsible for their contents or their use. By linking to a non- [website-name] website or webpage, [website-name] does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. [website-name] disclaims any responsibility for any harm resulting from your use of non- [website-name] websites and WebPages.</p>

<p><b>Copyright Infringement and DMCA Policy.</b><br/>
As [website-name] asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by [website-name] violates your copyright, you are encouraged to notify [website-name]. [website-name] will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. In the case of a visitor who may infringe or repeatedly infringes the copyrights or other intellectual property rights of [website-name] or others, [website-name] may, in its discretion, terminate or deny access to and use of the Website. In the case of such termination, [website-name] will have no obligation to provide a refund of any amounts previously paid to [website-name].</p>

<p><b>Intellectual Property.</b><br/>
This Agreement does not transfer from [website-name] to you any [website-name] or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with [website-name]. [website-name], www.[website-name].com, the [website-name] logo, and all other trademarks, service marks, graphics and logos used in connection with [website-name], or the Website are trademarks or registered trademarks of [website-name] or [website-name]\'s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any [website-name] or third-party trademarks.</p>

<p><b>Changes.</b><br/>
[website-name] reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. [website-name] may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.</p>

<p><b>Termination.</b><br/>
[website-name] may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your [website-name] account (if you have one), you may simply discontinue using the Website. Notwithstanding the foregoing, if you have a VIP Services account, such account can only be terminated by [website-name] if you materially breach this Agreement and fail to cure such breach within thirty (30) days from [website-name]\'s notice to you thereof; provided that, [website-name] can terminate the Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

<p><b>Disclaimer of Warranties.</b><br/>
The materials on [website-name]\'s web site are provided \'as is\'. [website-name] makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, [website-name] does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.</p>

<p><b>Limitation of Liability.</b><br/>
In no event will [website-name], or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to [website-name] under this agreement during the twelve (12) month period prior to the cause of action. [website-name] shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</p>

<p><b>General Representation and Warranty.</b><br/>
You represent and warrant that (i) your use of the Website will be in strict accordance with the [website-name] Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</p>

<p><b>Indemnification.</b><br/>
You agree to indemnify and hold harmless [website-name], its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys fees, arising out of your use of the Website, including but not limited to out of your violation this Agreement.</p>

<p><b>Site Terms of Use Modifications</b><br/>
[website-name] may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.</p>